In [19]:
import numpy as np
a = np.array([0,1,2,3,4,5,6,7,8,9])
a
#Task 1.1.1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
b=np.random.randint(1,100 , size=(3,3))
b
#Task 1.1.2

array([[32, 79, 71],
       [78,  3, 76],
       [51, 68, 87]])

In [21]:
a=a.reshape(2,5)
a
#Task 1.2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [22]:
a.dtype
#Task 1.3.1

dtype('int64')

In [23]:
a.size
#Task 1.3.2

10

In [24]:
a.shape
#Task 1.3.3

(2, 5)

In [27]:
import pandas as pd
df = pd.DataFrame(np.random.rand(5,3),
                  columns=["A","B","C"])
df
#Task 2.1

A         B         C
0  0.245284  0.706662  0.055604
1  0.108990  0.372312  0.466701
2  0.503720  0.810541  0.309385
3  0.081762  0.439849  0.274454
4  0.496484  0.687256  0.903965

In [34]:
print(df.head(2))
print(df.mean)

df["D"]= df["A"] + df["B"]
print(df)

#Task 2.2

          A         B         C         D
0  0.245284  0.706662  0.055604  0.245284
1  0.108990  0.372312  0.466701  0.108990
<bound method DataFrame.mean of           A         B         C         D
0  0.245284  0.706662  0.055604  0.245284
1  0.108990  0.372312  0.466701  0.108990
2  0.503720  0.810541  0.309385  0.503720
3  0.081762  0.439849  0.274454  0.081762
4  0.496484  0.687256  0.903965  0.496484>
          A         B         C         D
0  0.245284  0.706662  0.055604  0.951946
1  0.108990  0.372312  0.466701  0.481302
2  0.503720  0.810541  0.309385  1.314261
3  0.081762  0.439849  0.274454  0.521611
4  0.496484  0.687256  0.903965  1.183740


In [35]:
df=df[df["A"]>50]
df
#Task 3.3.1

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [36]:
df=df.sort_values(by="C", ascending=False)
df
#Task 3.3.2

Empty DataFrame
Columns: [A, B, C, D]
Index: []